### ISSUE TITLE
The last line in events.ts rewrites namespace of all previous lines

### ISSUE THREAD

**Issue by sjorobekov** [adonisjs/events#23]
## Prerequisites

The last line in events.ts rewrites namespace of all previous lines:

```
Event.on('new:organization', 'ChecklistListener.onNewOrganization').namespace('App/Checklist/Listeners')
Event.on('user:deactivated', 'StudyGroupsListener.onUserDeactivate').namespace('App/StudyGroups/Listeners')
```

```
[1698769693344] ERROR (myproject/14527 on Samats-MacBook-Pro-2.local): Cannot find module '/myproject/app/StudyGroups/Listeners/ChecklistListener'
Require stack:
- /myproject/node_modules/@adonisjs/fold/build/src/Ioc/ImportAliases.js
- /myproject/node_modules/@adonisjs/fold/build/src/Ioc/index.js
- /myproject/node_modules/@adonisjs/fold/build/index.js
- /myproject/node_modules/@adonisjs/application/build/index.js
- /myproject/node_modules/@adonisjs/assembler/build/src/requireHook/ioc-transformer.js
- /myproject/node_modules/@adonisjs/require-ts/node_modules/@poppinss/utils/build/src/esmRequire.js
- /myproject/node_modules/@adonisjs/require-ts/node_modules/@poppinss/utils/build/index.js
- /myproject/node_modules/@adonisjs/require-ts/build/src/Compiler/index.js
- /myproject/node_modules/@adonisjs/require-ts/build/index.js
- /myproject/node_modules/@adonisjs/assembler/build/src/requireHook/index.js
- /myproject/node_modules/@adonisjs/assembler/build/register.js
- internal/preload
    Error: Cannot find module '/myproject/app/StudyGroups/Listeners/ChecklistListener'
    Require stack:
    - /myproject/node_modules/@adonisjs/fold/build/src/Ioc/ImportAliases.js
    - /myproject/node_modules/@adonisjs/fold/build/src/Ioc/index.js
    - /myproject/node_modules/@adonisjs/fold/build/index.js
    - /myproject/node_modules/@adonisjs/application/build/index.js
    - /myproject/node_modules/@adonisjs/assembler/build/src/requireHook/ioc-transformer.js
    - /myproject/node_modules/@adonisjs/require-ts/node_modules/@poppinss/utils/build/src/esmRequire.js
    - /myproject/node_modules/@adonisjs/require-ts/node_modules/@poppinss/utils/build/index.js
    - /myproject/node_modules/@adonisjs/require-ts/build/src/Compiler/index.js
    - /myproject/node_modules/@adonisjs/require-ts/build/index.js
    - /myproject/node_modules/@adonisjs/assembler/build/src/requireHook/index.js
    - /myproject/node_modules/@adonisjs/assembler/build/register.js
    - internal/preload
        at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
        at Function.Module._load (node:internal/modules/cjs/loader:778:27)
        at Module.require (node:internal/modules/cjs/loader:1005:19)
        at require (node:internal/modules/cjs/helpers:102:18)
        at ImportAliases.resolve (/myproject/node_modules/@adonisjs/fold/build/src/Ioc/ImportAliases.js:99:23)
        at ImportAliases.resolveAsync (/myproject/node_modules/@adonisjs/fold/build/src/Ioc/ImportAliases.js:117:25)
        at Ioc.import (/myproject/node_modules/@adonisjs/fold/build/src/Ioc/index.js:280:42)
        at Ioc.makeAsync (/myproject/node_modules/@adonisjs/fold/build/src/Ioc/index.js:391:40)
        at IocResolver.call (/myproject/node_modules/@adonisjs/fold/build/src/Resolver/index.js:90:47)
        at /myproject/node_modules/@adonisjs/events/build/src/IocResolver/index.js:39:43  
```

## Package version
5.9

## Node.js and npm version
18

## Sample Code (to reproduce the issue)

```ts
// events.ts
Event.on('new:organization', 'ChecklistListener.onNewOrganization').namespace('App/Checklist/Listeners')
Event.on('user:deactivated', 'StudyGroupsListener.onUserDeactivate').namespace('App/StudyGroups/Listeners')
```

**Comment by thetutlage** [comment]
Yup, that's the expected behavior. The `namespace` method globally impacts all the event listeners.

If you need it at individual event level, then you can simply write the complete path within the listener argument.
